blank_issues_enabled: false
contact_links:
  - name: 🏗️ Missing Built-In
    url: https://github.com/mrjones2014/legendary.nvim/discussions/89
    about: Please comment on this GitHub Discussion for missing bult-ins
  - name: 🛠️ New `legendary.helpers` Function
    url: https://github.com/mrjones2014/legendary.nvim/discussions/90
    about: Please comment on this GitHub Discussion for `legendary.helpers` module changes
  - name: ❓️ Question
    url: https://github.com/mrjones2014/legendary.nvim/discussions
    about: Please create a GitHub Discussion for general questions
